# Generated by Django 4.0.10 on 2023-06-02 07:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024, null=True), default=list, size=None),
        ),
    ]
